version: "3.3"
services:
        web:
          image: "priyankchheta/test-docker:php"
          ports:
            - "8001:80"
          depends_on:
            - mysql
        mysql:
          image: priyankchheta/test-docker:sql
          volumes:
          - db_data:/var/lib/sql
          environment:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_DATABASE: mydatabase
volumes:
    db_data: {}
